[project]
name = "bamltest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "baml-py>=0.206.1",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
    "sympy>=1.14.0",
    "typing-extensions>=4.15.0",
]
